apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hellochart
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: hellochart
    weight: 100
  wildcardPolicy: None
