apiVersion: v1
kind: Template
metadata:
  name: source-template
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      annotations: null
      labels:
        app: '${APP_NAME}'
      name: '${APP_NAME}'
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: '${APP_NAME}'
      labels:
        app: '${APP_NAME}'
    spec:
      runPolicy: Serial
      triggers:
        - type: GitHub
          github:
            secret: secret101
        - type: Generic
          generic:
            secret: secret101
        - type: ImageChange
      source:
        git:
          uri: '${GIT_REPO_URL}'
        contextDir: helloworldservice
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'ubi8-openjdk-8:1.3'
            namespace: openshift
      output:
        to:
          kind: ImageStreamTag
          name: '${APP_NAME}:latest'
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: '${APP_NAME}'
      labels:
        app: '${APP_NAME}'
    spec:
      template:
        metadata:
          labels:
            name: '${APP_NAME}'
            app: '${APP_NAME}'
        spec:
          containers:
            - name: '${APP_NAME}'
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: RUN_ENV
                  value: OpenShift-With-SourceStrategy
          restartPolicy: Always
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - '${APP_NAME}'
            from:
              kind: ImageStreamTag
              name: '${APP_NAME}:latest'
      strategy:
        type: Rolling
      paused: false
      revisionHistoryLimit: 2
      minReadySeconds: 0
  - kind: Service
    apiVersion: v1
    metadata:
      annotations: null
      name: '${APP_NAME}'
      labels:
        app: '${APP_NAME}'
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: '${APP_NAME}'
      type: ClusterIP
      sessionAffinity: None
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: '${APP_NAME}'
      labels:
        app: '${APP_NAME}'
      annotations: null
    spec:
      to:
        kind: Service
        name: '${APP_NAME}'
        weight: 100
      port:
        targetPort: 8080-tcp
    wildcardPolicy: None
parameters:
  - name: APP_NAME
    description: Application name
    required: true
  - name: GIT_REPO_URL
    description: GIT Hub URL
    required: true
