deployment:
    image: quay.io/dhanamjaya/do400-deploying-environments
    tag: latest
    replicas: 1
    includeHealthChecks: true

route:
    host: hellochart-helm.apps-crc.testing

config:
    greeting: 'We are on a newer version now!'
