apiVersion: v1
kind: Template
metadata:
  name: ${APP_NAME}-template
  annotations:
    description: "${APP_NAME} Template"
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${APP_ENVIRONMENT}
    spec:
      selector:
        app:${APP_NAME}-${APP_ENVIRONMENT}
      replicas: 1
      template:
        metadata:
          labels:
            app: ${APP_NAME}-${APP_ENVIRONMENT}
        spec:
          containers:
            - name: ${APP_NAME}-${APP_ENVIRONMENT}
              image: quay.io/${QUAY_USER_OR_GROUP}/do400-deploying-environments:${APP_IMAGE_TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
      strategy:
        type: Rolling
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-${APP_ENVIRONMENT}
      name: ${APP_NAME}-${APP_ENVIRONMENT}
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: ${APP_NAME}-${APP_ENVIRONMENT}
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: ${APP_NAME}-${APP_ENVIRONMENT}
      labels:
        app: ${APP_NAME}-${APP_ENVIRONMENT}
    spec:
      to:
        kind: Service
        name: ${APP_NAME}-${APP_ENVIRONMENT}
      port:
        targetPort: 8080

parameters:
  - name: APP_NAME
    description: "Application name"
    required: true
  - name: QUAY_USER_OR_GROUP
    description: "Quay User/Group"
    required: false
    value: dhanamjaya
  - name: APP_ENVIRONMENT
    description: "Application environment"
    required: false
    value: "stage"
  - name: APP_IMAGE_TAG
    description: "Image Tag"
    required: false
    value: "latest"
