kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: simple-dev
spec:
  strategy:
    type: Source
  source:
    contextDir: helloworldservice
      type: Git
      git:
        uri: 'https://github.com/dhanamjaya123/openshiftdemos.git'
        ref: master
    output:
      to:
        kind: ImageStreamTag
        name: 'quay.io/dhanamjaya/do400-deploying-environments:latest'
    pushSecret:
      name: quay-credentials


