apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-dev
  labels:
    app: simple-dev
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/monodot/container-up'
    contextDir: helloworldservice
  strategy:
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: 'quay.io/dhanamjaya/do400-deploying-environments:latest'
