kind: BuildConfig
apiVersion: v1
metadata:
  name: simple-dev
  labels:
    application: simple-dev
spec:
  source:
    type: Git
    git:
      uri: https://github.com/dhanamjaya123/openshiftdemos.git
      ref: master
    contextDir: 'helloworldservice'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-11-ubi8
output:
  to:
    kind: ImageStreamTag
    name: quay.io/dhanamjaya/do400-deploying-environments:latest
pushSecret:
  name: quay-credentials
