kind: BuildConfig
apiVersion: quay.io/dhanamjaya
metadata:
  name: simple-dev
spec:
  nodeSelector: {}
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: 'https://github.com/dhanamjaya123/openshiftdemos'
      ref: master
    contextDir: 'helloworldservice'
  output:
    to:
      kind: DockerImage
      name: quay.io/dhanamjaya/do400-deploying-environments
    pushSecret:
      name: quay-credentials
