apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-dev
  labels:
    name: simple-dev
spec:
  triggers:
    - type: ConfigChange
  source:
    contextDir: helloworldservice
    type: Git
    git:
      uri: 'https://github.com/dhanamjaya123/openshiftdemos.git'
  sourceStrategy:
    type: Source
    from:
      kind: "ImageStreamTag"
      name: 'quay.io/dhanamjaya/do400-deploying-environments:latest'
