apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-dev
  labels:
    app: simple-dev
spec:
  source:
    type: Git
    git:
      uri: https://github.com/dhanamjaya123/openshiftdemos.git
    contextDir: helloworldservice
  strategy:
    type: Source
   sourceStrategy:
        name: 'quay.io/dhanamjaya/do400-deploying-environments:latest'

